os: linux
dist: xenial
language: python

python:
  - "3.7"

jobs:
  include:
    - name: "Python 3.7 on Linux Ubuntu"
      python: 3.7

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install -e .[tests,ci]
  - pip freeze

script:
  - pytest -m 'not mce_todo and not mce_known_bug' -x
  #- black -S -t py37 --check mce_lib_aws

after_success:
  - coveralls
  - codecov
