from .services import (
    acm,
    autoscaling,
    apigateway,
    apigateway,
    cloudformation,
    cloudfront,
    cloudsearch,
    dynamodb,
    ec2,
    ecs,
    efs,
    elasticache,
    elasticbeanstalk,
    elb,
    elbv2,
    es,
    lambda_,
    opsworks,
    rds,
    redshift,
    s3,
    sqs,
    sns
)


_AVAILABLES_RESOURCES = {
    'aws.acm.certificate': acm.Certificate,
    'aws.apigateway.restapis': apigateway.RestApi,
    'aws.autoscaling.autoScalingGroup': autoscaling.AutoScalingGroup,
    'aws.cloudfront.distribution': cloudfront.Distribution,
    'aws.cloudsearch.domain': cloudsearch.Domain,
    'aws.dynamodb.table': dynamodb.Table,
    'aws.ec2.instance': ec2.Instance,
    'aws.ecs.cluster': ecs.Cluster,
    'aws.efs.filesystem': efs.Filesystem,
    'aws.elasticache.cluster': elasticache.Cluster,
    'aws.elasticbeanstalk.application': elasticbeanstalk.Application,
    'aws.elb.loadbalancer': elb.Loadbalancer,
    'aws.elbv2.loadbalancer': elbv2.Loadbalancer,
    'aws.es.domain': es.Domain,
    'aws.lambda.function': lambda_.Function,
    'aws.opsworks.stack': opsworks.Stack,
    'aws.rds.db': rds.DbInstance,
    'aws.redshift.cluster': redshift.Cluster,
    'aws.s3.bucket': s3.Bucket,
    'aws.sqs.queue': sqs.Queue,
    'aws.sns.topic': sns.Topic
}
